### ISSUE TITLE
Node.js version trouble

### ISSUE THREAD

**Issue by jtilly** [conda-forge/code-server-feedstock#20]
With the latest build I'm running into this error on my Linux system:

```
Error: The module '/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Based on https://nodejs.org/en/download/releases/, this means that the code-server binary we're using was compiled with nodejs 14. When I update the recipe and pin nodejs at 14.* (instead of 12.*), things work fine. 

Full stacktrace:
```
$ code-server --auth none
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir ~/.local/share/code-server
info  code-server 3.4.0 69ad52907e8ea109345831d29da5425cb2a55047
info  HTTP server listening on http://127.0.0.1:8080
info    - No authentication
info    - Not serving HTTPS
Error: The module '/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.patchedRequire [as require] (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.patchedRequire [as require] (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:77:18)
    at t.load (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:16:119)
    at e.load (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:13:586)
    at i (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:29:259)
    at Object.errorback (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:29:383)
    at e.triggerErrorback (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:13:955)
    at /opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:13:659
    at ReadFileContext.callback (/opt/local/conda/envs/code-server/share/code-server/lib/vscode/out/vs/loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:256:13) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/local/conda/envs/code-server:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
code-server               3.4.0                         0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuv                     1.34.0               h516909a_0    conda-forge
nodejs                    12.16.1              h67efad7_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

**Comment by xhochy** [comment]
Can you make a PR to fix this?
